
# fly.toml app configuration file generated for cryp>
#
# See https://fly.io/docs/reference/configuration/ f>
#

app = 'crypto-market'
primary_region = 'sin'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
