name: Generate Traffic Badge

on:
  schedule:
    - cron: "0 2 * * *"  # Setiap hari jam 9 pagi (WIB)
  workflow_dispatch:

jobs:
  update-traffic-count:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Push traffic count to Redis via API
        run: |
          curl -X PUT https://crypto-price-on.vercel.app/api/traffic-badge \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
