name: Generate Traffic Badge & Deploy Bot

on:
  schedule:
    - cron: "0 2 * * *"  # Setiap hari jam 9 pagi (WIB)
  workflow_dispatch:

jobs:
  update-traffic-count:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Push traffic count to Redis via API
        run: |
          curl -X PUT https://crypto-price-on.vercel.app/api/traffic-badge \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"

  deploy-to-fly:
    needs: update-traffic-count
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Telegram Bot to Fly.io
        run: flyctl deploy --remote-only --app crypto-market
      - name: Set Telegram Webhook
        run: |
          curl -X POST https://api.telegram.org/bot${BOT_TOKEN}/setWebhook \
            -d "url=https://crypto-market.fly.dev/api/bot"
